---
#
# compose file to set up api-gw and orcehstra-stub for test of api-gw
#
version: '3.3'

services:
  api-gw:
    image: api_gw:latest
    ports:
      - 9091:9091
      - 9090:9090      
    tty: true
    extra_hosts:
      - "orchestra:172.20.0.1"

networks:
  breaker_test_net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"

